### ISSUE TITLE
Fix example in README for isWorkday

### ISSUE THREAD

**Issue by felippenardi** [raphamorim/calendario#1]
It seems that the example on README for the `isWorkDay` method is wrong: the same line of code returns true and false:

``` javascript
var calendario = require('calendario');
calendario.use('BR');

calendario.isWorkday(new Date('2015-05-01')); // false
calendario.isWorkday(new Date('2015-05-01')); // true
```

Shouldn't dates be different in each line?

**Comment by raphamorim** [comment]
True! good eye! @felippenardi. 

Fixed in https://github.com/raphamorim/calendario/commit/67f87a5df30eedc759e25fae1d2d3f50c34dcb8b
